# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            switch_user: ~
            form_login:
                login_path: security_login
                check_path: security_login
                remember_me: true
            logout:
                path: security_logout
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            anonymous: ~

    access_control:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MEMBRE, ROLE_ALLOWED_TO_SWITCH]
