# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user:
            entity: { class: AppBundle\Entity\User, property: email }
    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            switch_user: ~
            form_login:
                login_path: user_login
                check_path: user_login
                remember_me: true
            logout:
                path: user_logout
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            anonymous: ~
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 semaine
                path: /
                always_remember_me: true

    access_control:
        #routes du FMElfinderBundle
        - { path: ^/efconnect, role: ROLE_MEMBRE }
        - { path: ^/elfinder, role: ROLE_MEMBRE }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MEMBRE, ROLE_ALLOWED_TO_SWITCH]
