# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Class permettant de gerer l'authentification d'un utilisateur
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    # Ecoute une requete doctrine et hash le mot de passe utilisateur
    # s'il s'agit d'une requete d'enregistrement d'utilisateur
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    # Ecoute une requete doctrine et mets a jour les date de creation et de mise a jour d'un article
    app.doctrine.article_listener:
        class: AppBundle\Doctrine\ArticleListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.article_category_listener:
        class: AppBundle\Doctrine\ArticleCategoryListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.article_sub_category_listener:
        class: AppBundle\Doctrine\ArticleSubCategoryListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.user_listener:
        class: AppBundle\Doctrine\UserListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    # Ecoute un login utilisateur pour faire des choses juste apres
    app.listener.login_listener:
        class: AppBundle\Listener\LoginListener
        arguments: ['@security.token_storage', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
